const SPLASH = 'SPLASH';
const LOGIN = 'LOGIN';
const HOME = 'HOME';
const SIGNUP = 'SIGNUP';
const TAB_CONTAINER = 'TAB_CONTAINER';
const LEADERBOARD = 'LEADERBOARD';
const APPNAME = 'APPNAME';
const PROFILE = 'PROFILE';
const LEVEL_SCREEN = 'LEVEL_SCREEN';
const SETTING = 'SETTING';
const NOTIFICATION = 'NOTIFICATION';
const DISCUSS = 'DISCUSS';
const QUESTION_NAVIGATION = 'QUESTION_NAVIGATION';
const QUESTION_SCREEN = 'QUESTION_SCREEN';
const HINT_SCREEN = 'HINT_SCREEN';
const QUESTION_INFORMATION = 'QUESTION_INFORMATION';
const ANSWER = 'ANSWER';

export {
  SPLASH,
  LOGIN,
  HOME,
  SIGNUP,
  TAB_CONTAINER,
  LEADERBOARD,
  APPNAME,
  PROFILE,
  LEVEL_SCREEN,
  SETTING,
  NOTIFICATION,
  DISCUSS,
  QUESTION_SCREEN,
  HINT_SCREEN,
  QUESTION_NAVIGATION,
  QUESTION_INFORMATION,
  ANSWER,
};
