export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REQUEST_GOOGLE_LOGIN = 'REQUEST_GOOGLE_LOGIN';
export const GOOGLE_LOGIN_SUCCESSFUL = 'GOOGLE_LOGIN_SUCCESSFUL';
export const GOOGLE_LOGIN_ERROR = 'GOOGLE_LOGIN_ERROR';

export const REQUEST_CHANGE_PASSWORD = 'REQUEST_CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESSFUL = 'CHANGE_PASSWORD_SUCCESSFUL';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
