export const REQUEST_LIST_QUESTIONS = 'REQUEST_LIST_QUESTIONS';
export const LIST_QUESTIONS_SUCCESSFUL = 'LIST_QUESTIONS_SUCCESSFUL';
export const LIST_QUESTIONS_ERROR = 'LIST_QUESTIONS_ERROR';

export const REQUEST_GET_QUESTION_BY_ID = 'REQUEST_GET_QUESTION_BY_ID';
export const GET_QUESTION_BY_ID_SUCCESSFUL = 'GET_QUESTION_BY_ID_SUCCESSFUL';
export const GET_QUESTION_BY_ID_ERROR = 'GET_QUESTION_BY_ID_ERROR';

export const REQUEST_GET_SELECTED_TOPICID = 'REQUEST_GET_SELECTED_TOPICID';
export const GET_SELECTED_TOPICID_SUCCESSFUL =
  'GET_SELECTED_TOPICID_SUCCESSFUL';
export const GET_SELECTED_TOPICID_ERROR = 'GET_SELECTED_TOPICID_ERROR';
export const CLEAR_QUESTION_STATE = 'CLEAR_QUESTION_STATE';

export const REQUEST_GET_SELECTED_QUESTIONID =
  'REQUEST_GET_SELECTED_QUESTIONID';
export const GET_SELECTED_QUESTIONID_SUCCESSFUL =
  'GET_SELECTED_QUESTIONID_SUCCESSFUL';
export const GET_SELECTED_QUESTIONID_ERROR = 'GET_SELECTED_QUESTIONID_ERROR';

export const REQUEST_SUBMIT_QUESTION = 'REQUEST_SUBMIT_QUESTION';
export const SUBMIT_QUESTION_SUCCESSFUL = 'SUBMIT_QUESTION_SUCCESSFUL';
export const SUBMIT_QUESTION_ERROR = 'SUBMIT_QUESTION_ERROR';

export const REQUEST_GET_HINT_BY_QUESTION = 'REQUEST_GET_HINT_BY_QUESTION';
export const GET_HINT_BY_QUESTION_SUCCESSFUL =
  'GET_HINT_BY_QUESTION_SUCCESSFUL';
export const GET_HINT_BY_QUESTION_ERROR = 'GET_HINT_BY_QUESTION_ERROR';
