export const REQUEST_GET_USER_PROGRESS = 'REQUEST_GET_USER_PROGRESS';
export const GET_USER_PROGRESS_SUCCESSFUL = 'GET_USER_PROGRESS_SUCCESSFUL';
export const GET_USER_PROGRESS_ERROR = 'GET_USER_PROGRESS_ERROR';

export const REQUEST_GET_USER_PROFILE = 'REQUEST_GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESSFUL = 'GET_USER_PROFILE_SUCCESSFUL';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';

export const REQUEST_UPDATE_USER = 'REQUEST_UPDATE_USER';
export const UPDATE_USER_SUCCESSFUL = 'UPDATE_USER_SUCCESSFUL';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const REQUEST_GET_DAILY_STREAK = 'REQUEST_GET_DAILY_STREAK';
export const GET_DAILY_STREAK_SUCCESSFUL = 'GET_DAILY_STREAK_SUCCESSFUL';
export const GET_DAILY_STREAK_ERROR = 'GET_DAILY_STREAK_ERROR';

export const REQUEST_GET_LEADER_BOARD_DATA = 'REQUEST_GET_LEADER_BOARD_DATA';
export const GET_LEADER_BOARD_DATA_SUCCESSFUL =
  'GET_LEADER_BOARD_DATA_SUCCESSFUL';
export const GET_LEADER_BOARD_DATA_ERROR = 'GET_LEADER_BOARD_DATA_ERROR';

export const REQUEST_SUBMIT_FEEDBACK = 'REQUEST_SUBMIT_FEEDBACK';
export const SUBMIT_FEEDBACK_SUCCESSFUL = 'SUBMIT_FEEDBACK_SUCCESSFUL';
export const SUBMIT_FEEDBACK_ERROR = 'SUBMIT_FEEDBACK_ERROR';

export const REQUEST_GET_LEARNING_PROGRESS = 'REQUEST_GET_LEARNING_PROGRESS';
export const GET_LEARNING_PROGRESS_SUCCESSFUL = 'GET_LEARNING_PROGRESS_SUCCESSFUL';
export const GET_LEARNING_PROGRESS_ERROR = 'GET_LEARNING_PROGRESS_ERROR';